### ISSUE TITLE
npx compatibility

### ISSUE THREAD

**Issue by akx** [Automattic/calypso-codemods#6]
Hey there!

For some reason `calypso-codemods` seems to do nothing when run with [`npx`](https://github.com/npm/npx) (which, I know, isn't documented and thus I'd imagine not yet supported).

```
$ npx calypso-codemods commonjs-imports legacy-js/
Running commonjs-imports on legacy-js/
$
```

Compared to `yarn add --dev calypso-codemods` and then:

```
$ ./node_modules/.bin/calypso-codemods commonjs-imports legacy-js/
Running commonjs-imports on legacy-js/
Processing 13 files...
Spawning 7 workers...
All done.
$
```

It would be handy if this worked, since e.g. [`react-codemod`](https://github.com/reactjs/react-codemod#usage) endorses using `npx` for a fire-and-forget run.

**Comment by sirreal** [comment]
This seems to work fine:

```sh
npx calypso-codemods commonjs-imports code/to/transform
```
